chart:
  layout_name: Screener
  chart_timeframe: 1 minute
  bar_style: line
  headless: true
screener:
  shorttitle: Screener
  name: TTE Screener
alerts:
  batch_size: 3
  creation_delay: 1.5
  recalc_wait: 1.5
  start_fresh: false
webhook:
  url: https://stock-buddy-app.vercel.app/api/tte/combo
maintenance:
  interval: 300
progress:
  file: combo_progress.json
