from dotenv import load_dotenv
import os

load_dotenv()

# Profile path in chrome user data folder
PROFILE = 'Profile 2'

# Twitter API credentials
X_API_KEY = os.getenv('X_API_KEY')
X_API_SECRET = os.getenv('X_API_SECRET')
X_BEARER = os.getenv('X_BEARER')
X_ACCESS_TOKEN = os.getenv('X_ACCESS_TOKEN')
X_ACCESS_SECRET = os.getenv('X_ACCESS_SECRET')
X_CLIENT_ID = os.getenv('X_CLIENT_ID')
X_CLIENT_SECRET = os.getenv('X_CLIENT_SECRET')

# Discord webhook names
CURRENCIES_WEBHOOK_NAME = os.getenv('CURRENCIES_WEBHOOK_NAME')
US_STOCKS_WEBHOOK_NAME = os.getenv('US_STOCKS_WEBHOOK_NAME')
INDIAN_STOCKS_WEBHOOK_NAME = os.getenv('INDIAN_STOCKS_WEBHOOK_NAME')
CRYPTO_WEBHOOK_NAME = os.getenv('CRYPTO_WEBHOOK_NAME')

# Entry webhook links
CURRENCIES_ENTRY_WEBHOOK_LINK = os.getenv('CURRENCIES_ENTRY_WEBHOOK_LINK')
US_STOCKS_ENTRY_WEBHOOK_LINK = os.getenv('US_STOCKS_ENTRY_WEBHOOK_LINK')
INDIAN_STOCKS_ENTRY_WEBHOOK_LINK = os.getenv('INDIAN_STOCKS_ENTRY_WEBHOOK_LINK')
CRYPTO_ENTRY_WEBHOOK_LINK = os.getenv('CRYPTO_ENTRY_WEBHOOK_LINK')

# Exit webhook links
CURRENCIES_EXIT_WEBHOOK_LINK = os.getenv('CURRENCIES_EXIT_WEBHOOK_LINK')
US_STOCKS_EXIT_WEBHOOK_LINK = os.getenv('US_STOCKS_EXIT_WEBHOOK_LINK')
INDIAN_STOCKS_EXIT_WEBHOOK_LINK = os.getenv('INDIAN_STOCKS_EXIT_WEBHOOK_LINK')
CRYPTO_EXIT_WEBHOOK_LINK = os.getenv('CRYPTO_EXIT_WEBHOOK_LINK')

# Before/After webhook links
CURRENCIES_BEFORE_AFTER_WEBHOOK_LINK = os.getenv('CURRENCIES_BEFORE_AFTER_WEBHOOK_LINK')
US_STOCKS_BEFORE_AFTER_WEBHOOK_LINK = os.getenv('US_STOCKS_BEFORE_AFTER_WEBHOOK_LINK')
INDIAN_STOCKS_BEFORE_AFTER_WEBHOOK_LINK = os.getenv('INDIAN_STOCKS_BEFORE_AFTER_WEBHOOK_LINK')
CRYPTO_BEFORE_AFTER_WEBHOOK_LINK = os.getenv('CRYPTO_BEFORE_AFTER_WEBHOOK_LINK')
