'''All the names of the Discord webhooks we're using and their links'''

CURRENCIES_WEBHOOK_NAME = 'Currencies'
US_STOCKS_WEBHOOK_NAME = 'US Stocks'
INDIAN_STOCKS_WEBHOOK_NAME = 'Indian Stocks'
CRYPTO_WEBHOOK_NAME = 'Crypto'
INDICES_WEBHOOK_NAME = 'Indices'

CURRENCIES_WEBHOOK_LINK = 'https://DISCORD_WEBHOOK_REVOKED'
US_STOCKS_WEBHOOK_LINK = 'https://DISCORD_WEBHOOK_REVOKED'
INDIAN_STOCKS_WEBHOOK_LINK = 'https://DISCORD_WEBHOOK_REVOKED'
CRYPTO_WEBHOOK_LINK = 'https://DISCORD_WEBHOOK_REVOKED'
INDICES_WEBHOOK_LINK = 'https://DISCORD_WEBHOOK_REVOKED'